backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"

  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Description, name: body, widget: markdown }

  - name: "feature"
    label: "Feature"
    filter: {field: "type", value: "feature"}
    folder: "content/feature"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: body, widget: markdown }

