backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - { label: "Image Principale", name: "main_image", widget: "image" }
          - { label: "Presentation", name: "body", widget: "markdown" }

  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: 'service'}
      - { label: "Introduction", name: "description", widget: "text" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "feature"
    label: "Feature"
    folder: "content/feature"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Type", name: "type", widget: "hidden", default: "'feature'"}
      - { label: "Description", name: "body", widget: "markdown" }

