backend:
  name: git-gateway

media_folder: "/static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - { label: "Image Principale", name: "main_image", widget: "image" }
          - { label: "Presentation", name: "body", widget: "markdown" }

  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: "service"}
      - { label: "Introduction", name: "description", widget: "text" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "feature"
    label: "Feature"
    folder: "content/feature"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Couleur", name: "color", widget: "select", options: ["black", "yellow", "blue", "red", "purple", "orange", "pink", "grey", "green"]}
      - { label: "Type", name: "type", widget: "hidden", default: "feature"}

  - name: "client"
    label: "Clients"
    folder: "content/client"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: "client"}

  - name: "slide"
    label: "Slides"
    folder: "content/slide"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Texte", name: "text", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Type", name: "type", widget: "hidden", default: "slide"}

  - name: "coordonnees"
    label: "Coordonnées"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Valeur", name: "valeur", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["Phone", "Email", "Adress"}


